[package]
name = "nockapp"
version.workspace = true
edition.workspace = true

[features]
default = ["slog-tracing", "tracing-tracy"]
slog-tracing = []
trait-alias = []
bazel_build = []
tracing-tracy = ["dep:tracing-tracy"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bitvec = { workspace = true, default-features = false, features = ["alloc"] }
blake3 = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo", "color", "env"] }
dirs = { workspace = true }
ibig = { workspace = true }
nockvm = { workspace = true }
nockvm_macros = { workspace = true }

bincode = { workspace = true, features = ["serde"] }
byteorder = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
config = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
getrandom = { workspace = true }
gnort = { workspace = true }
intmap = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
signal-hook = { workspace = true }
signal-hook-tokio = { workspace = true, features = ["futures-v0_3"] }
tempfile = { workspace = true }
termimad = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "sync", "signal"] }
tokio-util = { workspace = true, features = ["rt"] }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true }
tracing-tracy = { workspace = true, optional = true, features = [
    "enable",
    "manual-lifetime",
    "ondemand",
] }
yaque = { workspace = true }

# Let's Encrypt and HTTPS support
axum-server = { workspace = true }
instant-acme = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde_json = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }
x509-parser = { workspace = true }

opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tonic.workspace = true

# Indexer support
rocksdb = "0.24"
hex = "0.4"

[dev-dependencies]

[lib]
name = "nockapp"
path = "src/lib.rs"
